apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: koto-ingress
  namespace: backend
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - "<USER-HUB-NO-PROTOCOL-ADDRESS>"
    - "<MESSAGE-HUB-NO-PROTOCOL-ADDRESS>"
    - "<MINIO-ENDPOINT-NO-PROTOCOL-ADDRESS>"
    secretName: koto-tls-backend
  rules:
  - host: <USER-HUB-NO-PROTOCOL-ADDRESS>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: user-hub-service
            port: 
              number: 12001
  - host: <MESSAGE-HUB-NO-PROTOCOL-ADDRESS>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: message-hub-service
            port: 
              number: 12002
  - host: <MINIO-ENDPOINT-NO-PROTOCOL-ADDRESS>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: message-hub-service
            port:
              number: 80
